### ISSUE TITLE
Dose finetrainers support multi-node training? 

### ISSUE THREAD

**Issue by cuijh26** [a-r-r-o-w/finetrainers#154]

**Comment by a-r-r-o-w** [comment]
I believe so, yes. I haven't tested on more than one node yet, but since we're only doing simple DDP, it should be easy to debug any problems hopefully. We rely on https://github.com/huggingface/accelerate for DDP, and it supports a variety of configurations for training - you can configure it for multi-node training by creating a config file with `accelerate config --config-file my_custom_config.yaml`

**Comment by cuijh26** [comment]
ok，thank you.
